# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_AUTHOR, ROLE_MOD, ROLE_ADMIN]
        ROLE_MOD:    ROLE_MOD
        ROLE_AUTHOR: ROLE_AUTHOR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: '/posts'
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/comments/delete/, role: ROLE_MOD}
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/tags/add, role: ROLE_ADMIN }
        - { path: ^/tags/edit/, role: ROLE_ADMIN }
        - { path: ^/tags/delete/, role: ROLE_ADMIN }
        - { path: ^/users/, role: ROLE_ADMIN }
        - { path: ^/posts/add, role: ROLE_AUTHOR}
        - { path: ^/posts/edit/, role: ROLE_AUTHOR}
        - { path: ^/posts/delete, role: ROLE_AUTHOR }
        - { path: ^/comments/edit/, role: ROLE_MOD}
        - { path: ^/comments/list, role: ROLE_MOD}